#dictcodes=(ANKS VPRM VJYP HVPD ABCH NGSH NSKS VLSS NSAP KDKS TSPD ATMH NRMI SRSS LKPK ENSK SRSG SKGL NDSG NMMD EKPD ANSH PRMM ENMS DNMS NNMR ANMG ANND EKKA NMMB SBRP ANKM ARMH NSMK ACPH ACSJ)
dictcodes=(NMMD)
for i in "${dictcodes[@]}"
do
  echo $i
  python3 automark.py $i
done
